services:
  backend:
    container_name: backend_api
    build:
      context: ./backend
      dockerfile: api.dockerfile
    image: backend_api
    ports:
      - "4000:4000"
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@app-db:5432/postgres?schema=public"
      REDIS_URL: "redis://app-redis:6379"
    depends_on:
      app-db:
        condition: service_healthy
      app-redis:
        condition: service_healthy
    restart: always

  worker:
    container_name: backend_worker
    build:
      context: ./backend
      dockerfile: worker.dockerfile
    image: backend_worker
    environment:
      JUDGE0_URL: "http://judge0-server:2358"
      DATABASE_URL: "postgresql://postgres:postgres@app-db:5432/postgres?schema=public"
      REDIS_URL: "redis://app-redis:6379"
    depends_on:
      app-db:
        condition: service_healthy
      app-redis:
        condition: service_healthy
    restart: always

  app-redis:
    image: redis:7.2-alpine
    container_name: app_redis
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - "6379:6379"
    volumes:               # <--- ADDED VOLUME MAPPING
      - app_redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    restart: always

  app-db:
    image: postgres:17
    container_name: app_db
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "postgres"
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 5s
      timeout: 3s
      retries: 5
    restart: always

volumes:
  pgdata:
  app_redis_data: